name: CI/CD with AWS Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/module10lab:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting deployment..."

            # Pull latest image
            docker pull tatoslover/module10lab:latest

            # Stop and remove old container
            docker stop module10lab-app || true
            docker rm module10lab-app || true

            # Run new container
            docker run -d \
              --name module10lab-app \
              -p 80:3000 \
              -p 3000:3000 \
              -e NODE_ENV=docker \
              --restart unless-stopped \
              tatoslover/module10lab:latest

            # Verify deployment
            sleep 5
            curl -f http://localhost:3000/health || echo "Health check failed"

            echo "Deployment completed!"
